version: '3'
services:

 mongo:
  image: mongo
  volumes:
   - /data/mongodb/db:/data/db
  ports:
   - "27016:27016"

 api:
  build: .
  command: node ./bin/www
  volumes:
   - .:/minimo2
  ports:
   - "3000:3000"
  links:
   - mongo
